# Generated by Django 4.1.4 on 2023-12-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_groups_media_message_decode_key_message_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/file'),
        ),
    ]
