# Generated by Django 4.1.4 on 2023-12-28 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conversation',
            table='Conversation',
        ),
        migrations.AlterModelTable(
            name='group_content',
            table='Group_content',
        ),
        migrations.AlterModelTable(
            name='groups',
            table='Groups',
        ),
        migrations.AlterModelTable(
            name='media',
            table='Media',
        ),
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
        migrations.AlterModelTable(
            name='participants',
            table='Participants',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
