# Generated by Django 4.1.4 on 2024-01-02 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0005_alter_conversation_table_alter_group_content_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='Admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groups',
            name='Created_by',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='Created_on',
            field=models.DateField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
