# Generated by Django 4.1.4 on 2023-12-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_remove_message_content_message_encrypted_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='encrypted_content',
            new_name='content',
        ),
    ]
