# Generated by Django 4.1.4 on 2023-12-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_rename_encrypted_content_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='decode_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
