# Generated by Django 4.1.4 on 2024-01-03 11:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0007_user_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_details',
            new_name='User_image',
        ),
        migrations.AlterModelTable(
            name='user_image',
            table='User_image',
        ),
    ]
