# Generated by Django 4.1.4 on 2024-01-03 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0008_rename_user_details_user_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_image',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_image', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='user_image',
            table=None,
        ),
    ]
