# Generated by Django 4.1.4 on 2023-12-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_message_decode_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
