# Generated by Django 4.1.4 on 2024-01-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_groups_image_alter_user_image_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
